### ISSUE TITLE
Breadcrumbs are only partially working

### ISSUE THREAD

**Issue by dkadioglu** [gade01/Rapier#31]
Hi,

I'm just testing your skin and I'm impressed about its look and functionality. Great work!
One thing, I noticed: In the breadcrumb bar, only the home icon is selectable. So, any deeper level than home cannot be reached.
See one of your screenshots, where I added a red box:
![image](https://cloud.githubusercontent.com/assets/1633773/25562398/85f99b3a-2d85-11e7-9041-7662b7fa5449.png)
I can select the home icon but, I cannot click on or even highlight 'MOVIES' or '2012'.
Is this an issue or by design?

Thanks and best

**Comment by gade01** [comment]
Hi dkadioglu.

Thanks a lot for the kind words and feedback.

That's intended behavoir.

Bread crumbs in Rapier is a visual indication of where you are - not intended to be clicked (which is why you can't navigate to them with a keyboard). 

Once leaving the home screen, you can navigate to and click the Home icon to return to the home screen.

A help could be navigating to the top options menu bar (clicking left or up from the library) and clicking the "Library" button for easy and fast access to everything in the current library.

**Comment by dkadioglu** [comment]
Thanks for your answer! If it is technically possible, what do you think about adding that possibility? Would you be willing to add it? IMHO this would improve navigation in Kodi a lot.

**Comment by gade01** [comment]
It's a very good idea and I'd love to add it.

Thing is, that it will require a ton of coding and testing..
I'll look at it when I have some more time. :)

**Comment by gade01** [comment]
I tried looking at this.
It will require too much coding as there are endless combinations for many of the breadcrumbs.

I'll close this for now.
